server:
  name: The minecraft server name
  notify:
    lagged:
      threshold: 15
notify:
  from: mengcraft@qq.com
  smtp:
    host: smtp.qq.com
    port: 25
    user: mengcraft
    pass: anyPassword
    sign: false